### ISSUE TITLE
Checklist working chatbot (Sun 9/4)

### ISSUE THREAD

**Issue by Joostrothweiler** [arjovanramshorst/chatbot#11]
### Functionality

**Chatbot functionality**
- [x] quit task functionality implemented (Lizzy)
- [x] better keyboard layout (Lizzy)
- [x] task should not be available if no units (Bjorn)
- [x] give more information per task (Bjorn)
- [x] keep serving tasks and user has to say quit (Bjorn)
- [x] solutions should be saved correctly when multiple questions (Bjorn)
- [ ] new user should get better introduction (e.g. the commands etc) (Lizzy)

**Platform functionality**
- [ ] review tasks (Arjo)
- [ ] requester can add tasks via API request (Arjo)

**Tasks**
External datasource (twitter)
- [x] sensemaking task designed
- [x] input api pipeline
- [x] output api pipeline
- [ ] chatbot functionality ready for this task (Lizzy)

Local datasource (Dropbox)
- [x] sensemaking task designed
- [ ] input api pipeline
- [ ] output api pipeline
- [ ] chatbot functionality ready for this task (Lizzy)

Content creation (image?)
- [x] sensemaking task designed
- [ ] input api pipeline
- [ ] output api pipeline
- [ ] chatbot functionality ready for this task (Lizzy)

### Deliverables
**Documentation (in README)**
- [x] write a deployment guide including seed operation (Bjorn)
- [x] write a document explaining the tasks (Lizzy)
- [ ] write documentation on how to use the pipelines (Joost)
- [ ] write documentation for the requester (Arjo)

**Presentation**
- [ ] make slides

**Evaluation**
- [ ] experimental setup (Lizzy)
- [ ] perform experiments
