### ISSUE TITLE
Must checklist Project Idea Document

### ISSUE THREAD

**Issue by Joostrothweiler** [arjovanramshorst/chatbot#12]
- [ ] The requester can define tasks via an API.
 - [x] The requester can view task results in ~~Google Sheets~~ CSV file.
 - [x] The system utilizes public data sources such as Twitter and Instagram.
 - [x] The system supports numbers, text, images, lists as types of input by the user.
 - [x] The chatbot can present tasks to the worker through Telegram in the form of chat messages.
 - [x] The chatbot has its own pool of tasks and is able to retrieve new tasks to supplement it.
 - [x] The chatbot can store solutions provided by the worker.
 - [x] The worker can start new, and end ongoing tasks through chatbot interaction.
