### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by BjornvdLaan** [arjovanramshorst/chatbot#24]
### Functionality

**Chatbot functionality**
- [x] new user should get better introduction (especially /quit) (e.g. the commands etc) (Lizzy))
- [x] a unique task should not be offered to the samen worker more than once. (Arjo)
- [x] a worker should not get to review his/her own answers to a task. (Arjo)
- [x] number in review should not be shown. (Arjo)
- [x] content creation review does not show an image, it gives [object Object] (Arjo)
- [x] Maybe leave out author of tweet → clutter (Bjorn)
- [x] Sentence of what kind of tweet the municipality likes to share (Lizzy)
- [x] Maybe replace ‘topology’ with ‘landscape’ (Joost)
- [x] Image category task: different votes from different people. If they have low agreement → send to expert / delete. If they have high agreement level → no need to do anything to the result. (Joost)
- [ ] Image categorization, ask why category? → open question (iedereen)
- [x] Show instructions while doing task in button (Lizzy)
- [x] Work on clarity. Whatever you show make it 100% clear (Lizzy)
- [x] Work on phrasing (Lizzy)
- [x] Work on styling (Lizzy) 
- [x] Make TEXT_LIST items bold (Arjo)
- [ ] Remove empty tasks from choose task (Arjo)

**Platform functionality**
- [x] review tasks (Arjo)
- [x] requester can add tasks via API request (Arjo)

**Tasks**
External datasource (twitter)
- [x] chatbot functionality ready for this task (Bjorn)
- [x] hide tweet id's (Bjorn)

Local datasource (Dropbox)
- [x] input api pipeline (Joost)
- [x] output api pipeline (Joost)
- [x] chatbot functionality ready for this task (Bjorn)

Content creation (image?)
- [ ] ~~input api pipeline (Joost)~~ Niet van toepassing
- [ ] ~~output api pipeline (Joost)~~ Niet van toepassing
- [x] chatbot functionality ready for this task (Bjorn)

### Deliverables
**Documentation (in README)**
- [x] write a deployment guide including seed operation (Bjorn)
- [x] write a document explaining the tasks (Lizzy)
- [x] write documentation on how to use the pipelines (Joost)
- [x] write documentation for the requester (Arjo)

**Presentation**
- [x] Why is it unique? Which are the main selling points of your application? (Jan Cees)
- [x] Describe your targeted audience. Which are your target groups of users? How do your accommodate their needs? (Jan Cees)
- [x] Which are the techniques (state-of-the-art, or innovative) that have been applied or developed in your project? (Jan Cees)
- [x] How did you tested your application? Were users involved? Which results did you obtain? (Lizzy/Joost)
- [x] Provide a convincing demonstration of your developed application, cross-checking with the initial requirements. (Arjo)

**Evaluation**
- [x] experimental setup (Lizzy)
- [x] perform experiments (Lizzy, Joost)
