### ISSUE TITLE
Extra's checklist

### ISSUE THREAD

**Issue by BjornvdLaan** [arjovanramshorst/chatbot#37]
- [ ] add user interface for the requester (lizzy)
- [ ] pipeline for instagram (joost+arjo)
- [ ] gamification elements such as botcoin (bjorn+arjo)
- [ ] add nlp outside task (jc+lizzy)
