### ISSUE TITLE
TODO list worker

### ISSUE THREAD

**Issue by BjornvdLaan** [arjovanramshorst/chatbot#8]
FEATURES
- [x] Save input as response
- [x] Support unit content type TEXT_LIST
- [ ] RASA NLP (Low priority)
- [x] User should be able to answer with a picture
- [x] Compare user message with expected response type
- [ ] Improve shortcut commands

SYSTEM
- [x] Deal with unexpected input during questions
- [x] Streamline complete workflow
- [x] Migrate to TGFancy for proper ordering of messages
- [x] Refactor code to make it less ugly (Low priority)
- [x] Bot should ask questions in right order (at the moment reversed)
